### PR TITLE
Changed directory structure of mathx

### PR DESCRIPTION
**Pull request by NK-Nikunj**
We have all the necessary headers in the `mathx` and the source files in `src`.

### CODE REVIEW

**Comment by kanav99** [comment]
Also, shouldn't we merge this PR only when the CMake integration is complete? Because it wont be usable in any way if we merge with changed directory structure but not proper installation.

**Comment by NK-Nikunj** [comment]
do we really need mathx.cpp and mathx.h?

**Comment by kanav99** [comment]
We wont need `mathx.cpp` now as we have different repository for that, but `mathx.h` would surely be needed which would be included by user.

**Comment by NK-Nikunj** [comment]
@kanav99 rightly pointed. We have two options as of now. I'll add the cmake integration as well and then merge. Other option is to merge it now and use it the previous commit to test the code since they too will be added as a pr.

**Comment by NK-Nikunj** [comment]
I'll update `mathx.h` then.

**Comment by kanav99** [comment]
Okay. Both options are fine. Make sure you complete the CMake integration quickly if we merge this.

**Comment by NK-Nikunj** [comment]
@kanav99 changes wrt `mathx.h` have been made. Yes, I will try to complete it all by the end of this week.

**Pull request merged**
